# Parameters
nc: 22  # Number of classes (beállításod szerint)
scales:  # Model compound scaling constants
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.50, 512]

# YOLO11 Backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # P2/4
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]  # P3/8
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]  # P4/16
  - [-1, 2, C3k2, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # P5/32
  - [-1, 2, C3k2, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # Spatial Pyramid Pooling
  - [-1, 2, C2PSA, [1024]]  # Attention Mechanism

# YOLO11 Head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]]  # Concatenate with backbone P4
  - [-1, 2, C3k2, [512, False]]

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]]  # Concatenate with backbone P3
  - [-1, 2, C3k2, [256, False]]  # Small scale (P3/8)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]]  # Concatenate with P4
  - [-1, 2, C3k2, [512, False]]  # Medium scale (P4/16)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]]  # Concatenate with P5
  - [-1, 2, C3k2, [1024, True]]  # Large scale (P5/32)

  - [[16, 19, 22], 1, Detect, [nc]]  # Detect layers with proper input list
