# YOLOv11 konfiguráció
nc: 80  # Osztályok száma (pl. COCO dataset = 80)
depth_multiple: 0.33  # Modell mélységének skálázása
width_multiple: 0.50  # Modell szélességének skálázása
anchors:
  - [10,13, 16,30, 33,23]  # P1
  - [30,61, 62,45, 59,119] # P2
  - [116,90, 156,198, 373,326] # P3

# Backbone (CNN rétegek)
backbone:
  - [-1, 1, Conv, [64, 3, 1]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 3, C3, [128]]

# Fej (Prediction)
head:
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 3, C3, [256]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 3, C3, [512]]
  - [-1, 1, Detect, [nc]]  # YOLO fej
